### ISSUE TITLE
Image resolutions

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#120]
1. Write a python script which can always **resize a picture to a fixed height while maintaining the aspect ratio** This would be the height of the container which we use to display the images in our events page or elsewhere. It can take size as the input. We of course want to keep the original picture somewhere in backup.

2. Use these images in the slideshow on events tab. Make sure that the original image is large enough that after resizing, the width is greater or equal to the width of the container. If greater, you can symetrically clip the image on both ends (left and right). This is a simple CSS thing.

**Comment by cheekujodhpur** [comment]
@TheFlash98 This is high priority to me. Are you free today? I will help you or do it myself otherwise.

**Comment by CodeMaxx** [comment]
resize.py was used so that the SoC page showing all the projects is symmetric and doesn't fuck up

**Comment by cheekujodhpur** [comment]
@CodeMaxx Oh! Okay, but in retrospect, we should've resized only to height/width while maintaining the aspect ratio, and clipped the extra, otherwise it's ugly. Well, I'm repeating what I've already said.

Also, http://wncc-iitb.org/events/11-GoogleIOExtended17.html#nav 
The first image, the image is vertical but the browser rotates it. These modern browsers are fucktards. We have to specify 'image-orientation: from-image' in CSS to fix this, but then that makes the slideshow size change up and down. @nihal111 I'm throwing out vertical images. Either come up with a nice way to arrange them, or make a note in journal that we take landscape pictures for website.

**Comment by TheFlash98** [comment]
@cheekujodhpur I can work on this tomorrow! I just saw it.

**Comment by nihal111** [comment]
@TheFlash98 tomorrow never dies

**Comment by nihal111** [comment]
Fixed by #161. Closing
