### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by ishan00** [nihal111/WnCC#129]
A Team page should be added containing the list of people (Managers, Conveners, Volunteers).

**Comment by TheFlash98** [comment]
The entire tty0 should be there. WnCC Family rather. 😄

**Comment by martiansideofthemoon** [comment]
With photographs, bios, webpage / GH links :smile:

**Comment by grubdragon** [comment]
tty0 meetup on movie night?

**Comment by grubdragon** [comment]
I think we are done here :heart_eyes:
