### ISSUE TITLE
Improper Height of Iframe element

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#13]
http://wncc-iitb.org/soc_projects/17-rattlesnake-ranveer.html

The leaderboard cannot be properly seen on this page.

**Comment by nihal111** [comment]
I can change the height but it is scrollable now, isn't that desired?

**Comment by cheekujodhpur** [comment]
Scrollable is desired, but the current height views me only 2 or 3
cells...at least 10 cells dikhne chahiye...

Make it 500px
