### ISSUE TITLE
Add Scratch Day 2017 to events

### ISSUE THREAD

**Issue by ydidwania** [nihal111/WnCC#135]
The last added event in the 2017 tab is the Yahoo! HACKu. Add a markdown file for Scratch Day 2017 in [_events](https://github.com/nihal111/WnCC/tree/master/_events) and add images in [_event-images](https://github.com/nihal111/WnCC/tree/master/event_images) .

**Comment by tezansahu** [comment]
I wish to solve this issue. Pls let me know about the details

**Comment by nihal111** [comment]
Hello! Sure, just have a look at the events folder and see how events are created. Should be fairly easy. We will provide you with the images soon.

**Comment by tezansahu** [comment]
Thanks

**Comment by tezansahu** [comment]
Pls do send me the images at the earliest. I have already worked on the outline of the event

**Comment by grubdragon** [comment]
Hey! We get your eagerness, but something you must learn is you aren't always gonna get instant replies. Here, and in general, on all repos you work on in the future

**Comment by tezansahu** [comment]
Ok

**Comment by tezansahu** [comment]
@nihal111 , Requesting you to send the images to me so that i could work on them. Also, pls let me know what is meant by "weight" in the markdown files of all the events.

**Comment by nihal111** [comment]
@tezansahu  Here you go. The zip has the images you need. Sorry for the delay.
[Desktop.zip](https://github.com/nihal111/WnCC/files/1424334/Desktop.zip)

Weight in the markdown files is meant for determining the order in which the events appear.
Look for the line `{% assign eventList = eventList | sort: "weight" %}` in `_pages/events.md`

**Comment by tezansahu** [comment]
Check out my PR #154 
Let me know if anything else is required

**Comment by tezansahu** [comment]
Check out my PR #155. It contains the list of winners of the competition in the file. Hope that works

**Comment by tezansahu** [comment]
Check out my PR #156. I have fixed the issues with the extensions of image files
