### ISSUE TITLE
Change ribbon of completed SoC Projects

### ISSUE THREAD

**Issue by TheFlash98** [nihal111/WnCC#140]
There were some SoC Projects which were completed during this summer. Their Ribbon however still says `In Progress`. Need to update it to `Complete`. Should be fairly simple how the code is written for Completed Projects.

**Comment by starlord1311** [comment]
which all projects are complete?

**Comment by starlord1311** [comment]
i want to take up this issue

**Comment by nihal111** [comment]
@TheFlash98 Can you provide the list?

**Comment by TheFlash98** [comment]
Panaroma in Cam Scanner is one of the completed projects. Send a PR for that.

**Comment by thenotsodarkknight** [comment]
@TheFlash98 This issue is over.

**Comment by grubdragon** [comment]
Could you link in the relevant PRs @thenotsodarkknight ?

**Comment by thenotsodarkknight** [comment]
@grubdragon [this PR](https://github.com/nihal111/WnCC/pull/158)

**Comment by e-aakash** [comment]
Completed by this PR: https://github.com/nihal111/WnCC/pull/228 and this commit: https://github.com/nihal111/WnCC/commit/c81013bfc69b73fdff7d3efb245a9de169238894
