### ISSUE TITLE
Learn More button

### ISSUE THREAD

**Issue by nihal111** [nihal111/WnCC#26]
The learn more button feels less like a button.
Keep the current hover color as default and make the transition on hover to an even darker shade of grey. Or do something like that which makes it look more like a button.

**Comment by cheekujodhpur** [comment]
![screenshot from 2017-04-06 21-16-51](https://cloud.githubusercontent.com/assets/5952063/24763237/66b04c8a-1b0e-11e7-99fe-876c51e2a67d.png)
![Uploading Screenshot from 2017-04-06 21-16-42.png…]()


You can see from these two images. It does not really help much. Perhaps a translate by (1px, 1px) :stuck_out_tongue: might help?
