### ISSUE TITLE
Requirement of Dataset 

### ISSUE THREAD

**Issue by AshuKV** [nihal111/WnCC#266]
please do provide dataset and do mention the requirements for this '19-ritwick-shubham-mri-ct.md'..

**Comment by cheekujodhpur** [comment]
@e-aakash wtf is this?

**Comment by e-aakash** [comment]
@cheekujodhpur I think he is asking for the dataset used for [Automated Fiducial Localization](https://www.wncc-iitb.org/soc_projects/19-ritwick-shubham-mri-ct.html) project (which happened in 2017 summers).

**Comment by AshuKV** [comment]
> @cheekujodhpur I think he is asking for the dataset used for [Automated Fiducial Localization](https://www.wncc-iitb.org/soc_projects/19-ritwick-shubham-mri-ct.html) project (which happened in 2017 summers).

Yes you are right

**Comment by e-aakash** [comment]
Mentors have the dataset, we don't store them. Hence closing this issue.
