### ISSUE TITLE
Improve arrows for slider

### ISSUE THREAD

**Issue by nihal111** [nihal111/WnCC#31]
The slider (can be found [here](http://wncc-iitb.org/events/1-rattlesnake.html)) has weird looking small blue colored arrows. Improve these to kind of look like these-
![screenshot from 2017-04-09 13 56 07](https://cloud.githubusercontent.com/assets/13916513/24835924/62fdd240-1d2c-11e7-92ab-19a4c5017359.png)

**Comment by cheekujodhpur** [comment]
if we include bootstrap glyphicons, this is easy. But I don't think the idea of having to include so much just for this is a good one.

I have a similar argument against using the 'slick' library as we are using now for slideshow. I would want to replace the whole thing with a pure CSS/JS code which is inline.
Let us see what can I do

**Comment by cheekujodhpur** [comment]
#36 solves this.

**Comment by nihal111** [comment]
Thanks @cheekujodhpur
