### ISSUE TITLE
Make Sliders Responsive

### ISSUE THREAD

**Issue by nihal111** [nihal111/WnCC#35]
The image sliders currently aren't responsive.
Make them responsive.

**Comment by TheFlash98** [comment]
<img width="1280" alt="screen shot 2017-04-10 at 15 14 59" src="https://cloud.githubusercontent.com/assets/22732781/24855883/8014b2b6-1e00-11e7-8afc-e1211266cadc.png">
You sure?

**Comment by nihal111** [comment]
![screenshot_2017-04-10-15-18-20_com android chrome](https://cloud.githubusercontent.com/assets/13916513/24856066/10fc1364-1e01-11e7-8698-3255c16da40a.png)

![screenshot_2017-04-10-15-18-05_com facebook orca](https://cloud.githubusercontent.com/assets/13916513/24856077/195836a0-1e01-11e7-9d37-e9119bb2fa00.png)

**Comment by nihal111** [comment]
The first screenshot is from Chrome on my phone, the other is from the browser instance that opens by default using Messenger.
Weird.
I think we can't do anything about this.

**Comment by TheFlash98** [comment]
This is weird.....
