### ISSUE TITLE
move the slick directory deeper in the tree

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#38]
The directory for `slick` which handles the image slider lies in the home directory. This is unwanted for a long run. it's resources should be moved to the respective `js` and `css` folder and all mentions of it corrected accordingly

**Comment by Owl-A** [comment]
Please, review #82

**Comment by nihal111** [comment]
Thanks @Owl-A .
@TheFlash98  Can you confirm that #82 fixes this?
