### ISSUE TITLE
no text in event name buttons

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#39]
![screenshot from 2017-04-15 11-30-34](https://cloud.githubusercontent.com/assets/5952063/25061232/265c0f1c-21cf-11e7-83a8-284cec3ddd7e.png)

this is not a css problem. the text is simply missing.

**Comment by TheFlash98** [comment]
But then.. If you click on it the text does appear?

**Comment by cheekujodhpur** [comment]
fixed upstream
