### ISSUE TITLE
update the about text in footer

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#40]
It still says "STAB" and the web link goes to stab-iitb.org/wncc

These should be changed, eventually.

**Comment by cheekujodhpur** [comment]
@Owl-A It's an easy thing. I command thee :stuck_out_tongue:

**Comment by Owl-A** [comment]
As you say, your highness 😂

**Comment by Owl-A** [comment]
I did change STAB to ITC (formerly STAB) but we are still waiting for the impending URL change from STAB's side, so we better not close this issue yet .

**Comment by TheFlash98** [comment]
The should redirect to www.wncc-iitb.org right?

**Comment by nihal111** [comment]
Fixed by https://github.com/nihal111/WnCC/pull/151
Closing.

**Comment by e-aakash** [comment]
The links and content have been updated, hence closing this issue.
