### ISSUE TITLE
The long titles overflow the bar in sidebar for soc projects

### ISSUE THREAD

**Issue by cheekujodhpur** [nihal111/WnCC#41]
http://wncc-iitb.org/soc_projects/11-scilab-videoplayer.html

On the left sidebar, projects like "Develop GUI for openmodelica usin..." overflow the container. We have to find a solution to this

**Comment by nihal111** [comment]
https://github.com/nihal111/WnCC/commit/d1bffa480cd37ebdaa0738baa15aea4f0f7e467f fixes it.
