### ISSUE TITLE
Add year tabs for 2013, 2014, 2015 in Events

### ISSUE THREAD

**Issue by nihal111** [nihal111/WnCC#42]
Currently there are only two tabs in Events- 2016, 2017
More tabs can be added and code replication can be dealt with using a for loop in Liquid Template as:
```
{% for i in (2013..2017) %}
  {{ i }}
{% endfor %}
```

**Comment by Owl-A** [comment]
#70 addresses this issue
#doing things professionally :smile:

**Comment by nihal111** [comment]
This was much needed. Thanks @Owl-A  :D
#70 tests out.
