### ISSUE TITLE
Events page row breaking

### ISSUE THREAD

**Issue by nihal111** [nihal111/WnCC#72]
Thanks to @Owl-A, the event page now has wonderful tabs and shows events filtered on a year basis.
But the row breaking doesn't quite work properly. Liquid's cycle is being used to send every fourth event to the next row. This somehow breaks when doing the capture for `thecycle` inside an `if` block here- https://github.com/nihal111/WnCC/blob/master/_pages/events.md

**Comment by Owl-A** [comment]
#73 merged with master, merge with production please :stuck_out_tongue:
