### ISSUE TITLE
weight wise sorting not working in events

### ISSUE THREAD

**Issue by Owl-A** [nihal111/WnCC#77]
when sort is used on eventList in events.md page like soc.md the row creation loop somehow mess up 
we need to find a way to sort them by weight

**Comment by cheekujodhpur** [comment]
@Owl-A If I can guess well, it is sorting it on date by default? 

@nihal111 We had a problem like this in early days as well, right? Do you remember what did we do about it?

**Comment by nihal111** [comment]
@cheekujodhpur Did we? I never gave a damn about sorting :stuck_out_tongue:

**Comment by grubdragon** [comment]
#105 Fixed hopefully

**Comment by TheFlash98** [comment]
I don't think we should sort them by weight. It's getting a bit random @grubdragon . By default they are being sorted by date. Although the latest event goes to the end, we could reverse that!

**Comment by grubdragon** [comment]
Will resend PR again, abhi ditch kar diya, abhi ke liye SoC pull karo

**Comment by grubdragon** [comment]
Redone
#106

**Comment by Owl-A** [comment]
Fixed😬 nice work @grubdragon
